### ISSUE TITLE
link to maltab

### ISSUE THREAD

**Issue by blemasso** [Shinyhero36/Leboncoin-API-Wrapper#1]
Hi, I am a Matlab user and I would love to use (or to call) your code from matlab.
do you think that it would be possible to help me out to do that?

thanks!
Ben

**Comment by Shinyhero36** [comment]
Hi, I am **not** a Matlab user, so this might be a bit difficult to help you.
What do you pllna to do?
By any chance do you speak french?

**Comment by blemasso** [comment]
salut,

En faite, j’avais fais une petite app il y a quelques temps qui avait pour but d’analyser le prix de vente de certains produit.
Mon appli est développée sous matlab. Puis un jour, le boncoin a changé son site et je n’arrive plus à récupérer les info ce que ton code fait très bien!
c’est pourquoi je voulais appeler ton code depuis le miens :)
Je suis suis pas très bon en python (j’essai de my mettre..). Ca serait possible de faire une petite fonction python qui prends en entrée la requête du boncoin et qui génère un fichier type csv ou autre ?

et toi, tu as développé cette API dans quel but?

bye,
Ben

**Comment by Shinyhero36** [comment]
@blemasso Okay alors si je comprends bien tu veux en entrée une requête vers l'API de leboncoin et les résultats en sortie dans un fichier .csv c'est ca?
Ca doit être faisable en python.

J'avais développé l'API pour l'intégrer aux Assistant vocaux de Google.

**Comment by Shinyhero36** [comment]
@blemasso Je viens de réécrire le code. Est-ce que des données au format JSON c'est bon pour toi.
Sinon pour le fichier .csv tu veux quoi comme catégories en colonnes?

**Comment by blemasso** [comment]
oui le json ça me convient bien! merci (désolé pour ma réponse tardive...)

**Comment by Shinyhero36** [comment]
Okay, c'est bon j'ai fini j'ai mis un code fonctionnel dans la branch [**MatLab**](https://github.com/Shinyhero36/Leboncoin-API-Wrapper/tree/MatLab) qui une fois la recherche fait, enregistre les résultats dans un fichier json.

Regarde comment j'ai fait dans le fichier [**test.py**](https://github.com/Shinyhero36/Leboncoin-API-Wrapper/tree/MatLab/test.py).

Si tu as d'autres questions, je reste disponible!

**Comment by blemasso** [comment]
merci!
je vais tester ça dès que possible
