### ISSUE TITLE
Add a changelog and versions

### ISSUE THREAD

**Issue by brunetton** [Shinyhero36/Leboncoin-API-Wrapper#10]
Hi, what do you think about adding a changelog file, and versioning ? 
Now that we've added the setup.py file, that contains a version, this could be great to increment it on (at least) major changes, what do you think ? :)

**Comment by Shinyhero36** [comment]
Hi, that sounds like a very good idea !!

**Comment by Shinyhero36** [comment]
# Changelog
All notable changes to this project will be documented in this file.

## [Unreleased]

## Version 0.X.X
**Released on ...**

### Added
 - lorem ipsum
 - lorem ipsum
 - lorem ipsum

### Changed
 - lorem ipsum
 - lorem ipsum
 - lorem ipsum
 
### Removed
 - lorem ipsum
 - lorem ipsum
 - lorem ipsum


Is it okay with something like this?

**Comment by brunetton** [comment]
Yes I think this is more than ok :)
