### ISSUE TITLE
ModuleNotFoundError: No module named 'dataclasses' when using in new venv

### ISSUE THREAD

**Issue by brunetton** [Shinyhero36/Leboncoin-API-Wrapper#13]
Looks like `setup.py` haven't been updated when Advertisement class was introduced ;)

**Comment by Shinyhero36** [comment]
Dataclasses modules is available for Python 3.7 and above.
What do you mean by 
> Looks like `setup.py` haven't been updated when Advertisement class was introduced ;)

**Comment by brunetton** [comment]
> What do you mean by
> > Looks like `setup.py` haven't been updated when Advertisement class was introduced ;)

`dataclasses` dependency should be added to `install_requires` of `setup.py`

**Comment by Shinyhero36** [comment]
I thought it came by default with Python 3.7 and above. 
I don't know if it is still relevant to transpose the json response into a dataclass. As if the json changes over time, the class will be broken. Anyway I'll add it for now.

What do you think?

**Comment by brunetton** [comment]
> I thought it came by default with Python 3.7 and above.

🤔 it's always a mess to know whether a package is a standard package or not. But yes, my bad this is a [standard python package](https://docs.python.org/3/library/dataclasses.html?highlight=dataclasses) you're right. So I don't know why I got this error. Anyway

> I don't know if it is still relevant to transpose the json response into a dataclass. As if the json changes over time, the class will be broken. Anyway I'll add it for now.
> 
> What do you think?

I agree with the fact that I don't think that it's a good option to make a  hard-coded dataclass from answer. I prefer to navigate thought lists and dicts without having to ask myself "how this have been transposed in a model ? Where's this data ?"

In that case (if you agree to remove this model) this issue is a non-sense of course

**Comment by brunetton** [comment]
I got this again.
After checking, I was running on Python 3.6. So I think this should be a good idea to explicitely add `dataclasses` dependency in setup.py to make the lib works with (hopefully) all Python versions.
