### ISSUE TITLE
Crash when a captcha is returned by API: KeyError: 0

### ISSUE THREAD

**Issue by brunetton** [Shinyhero36/Leboncoin-API-Wrapper#14]
Sometimes (quite randomly), the API answer a captcha URL. Example: 

```json
{"url": "https://geo.captcha-delivery.com/captcha/?initialCid=AHrlqAAAAAMAVaU8ADn3DK8AUkBMug==&hash=05B30BD9055986BD2EE8F5A199D973&t=fe&s=285"}
```

Stacktrace (from my project [leboncoin-auto-scrapper](https://github.com/brunetton/leboncoin-auto-scrapper)):

```
nov. 17 00:24:43 raspberrypi bash[20173]: Traceback (most recent call last):
nov. 17 00:24:43 raspberrypi bash[20173]:   File "./leboncoin_scrapper.py", line 141, in <module>
nov. 17 00:24:43 raspberrypi bash[20173]:     main()
nov. 17 00:24:43 raspberrypi bash[20173]:   File "./leboncoin_scrapper.py", line 55, in main
nov. 17 00:24:43 raspberrypi bash[20173]:     scrap()
nov. 17 00:24:43 raspberrypi bash[20173]:   File "./leboncoin_scrapper.py", line 74, in scrap
nov. 17 00:24:43 raspberrypi bash[20173]:     results = search(lbc, config['searches'], config['price']['min'], config['price']['max'])
nov. 17 00:24:43 raspberrypi bash[20173]:   File "./leboncoin_scrapper.py", line 123, in search
nov. 17 00:24:43 raspberrypi bash[20173]:     lbc.searchFor(query)
nov. 17 00:24:43 raspberrypi bash[20173]:   File "/usr/local/lib/python3.6/site-packages/leboncoin_api_wrapper/leboncoin.py", line 101, in searchFor
nov. 17 00:24:43 raspberrypi bash[20173]:     category = self._get_category(query)
nov. 17 00:24:43 raspberrypi bash[20173]:   File "/usr/local/lib/python3.6/site-packages/leboncoin_api_wrapper/leboncoin.py", line 89, in _get_category
nov. 17 00:24:43 raspberrypi bash[20173]:     return str(res[0]["cat_id"])
nov. 17 00:24:43 raspberrypi bash[20173]: KeyError: 0
```

Similar occurred for Npm Leboncoin team: https://github.com/tdurieux/leboncoin-api/issues/53

In that case we'd maybe retry ? Or wait and retry ? (I didn't read the entiere node thread, I don't know how did they deal with this)

For now a generic exception is raised. I propose to implement a "cleaner" and dedicated Exception with an error message that points to this issue for now.
This would permit to lib's users to do something like:

```python
from leboncoin_api_wrapper import CaptchaException

[...]

try:
        lbc.searchFor(query)
        result = lbc.execute()
except CaptchaException:
        # Do what you want with it. Probably a sleep and retry
```

What do you think about this ?

**Comment by Shinyhero36** [comment]
I never had this error before. How many requests(rate per minute or per second) do you make? Cloudscraper is supposed to handle captcha...
Retrying something like three times sounds good to me.
I am okay with raising an exception

What to you mean by implementing a "cleaner"?

**Comment by brunetton** [comment]
> I never had this error before. How many requests(rate per minute or per second) do you make? Cloudscraper is supposed to handle captcha...

I'm doing:
- each 20 minutes (approx)
   - do 8 requests, waiting 8 seconds between each

> Retrying something like three times sounds good to me.
> I am okay with raising an exception

Great

> What to you mean by implementing a "cleaner"?

It's cleaner to raise a dedicated exception, clearly showing that a captcha has been received than only raising `KeyError: 0`

**Comment by Shinyhero36** [comment]
Okay I thought you were spamming API calls.
Indeed it's better to raise something else than `KeyError: 0`.

Did you already implement the Exception?

**Comment by brunetton** [comment]
> Did you already implement the Exception?

I'll do a PR when I did :)

**Comment by brunetton** [comment]
After some digging, it appeared that this error is due to my local configuration (OpenSSL version)

I didn't noticed this alert in logs:
> nov. 17 13:22:56 raspberrypi bash[30442]: DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.1.0j  20 Nov 2018) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected Captcha or cloudflare 1020 blocks.

So ... finally I don't think that we should create a special Exception for this case that is not "normal".

I only checked API result type and crashed a little before with a clearer error message.

**Comment by Shinyhero36** [comment]
Okay I will close the issue then

**Comment by brunetton** [comment]
I'm not sure if there's a direct link (it can be a coincidence) but since yesterday I deactivated `autoCatgory` in `searchFor()` call and I didn't get any captcha.
Before that, I got this case at least 10 times a day.

I presume this is because when `autoCatgory` is True (by default) Leboncoin-API-Wrapper triggers 2 API calls without any wait between them. This is probably that triggered the captcha. Not sure for now; I'll wait some days to be sure.

By the way I still don't see any case where `autoCatgory` can be usefull, but this is another story !

**Comment by Shinyhero36** [comment]
> I presume this is because when `autoCatgory` is True (by default) Leboncoin-API-Wrapper triggers 2 API calls without any wait between them. This is probably that triggered the captcha. Not sure for now; I'll wait some days to be sure.

That is what I was thinking too.

> By the way I still don't see any case where `autoCatgory` can be usefull, but this is another story !

The more is see the `autoCatgory`, the more i think it's useless. But yes that's an other story.

**Comment by brunetton** [comment]
> > By the way I still don't see any case where `autoCatgory` can be usefull, but this is another story !
> 
> The more is see the `autoCatgory`, the more i think it's useless. But yes that's an other story.

Let's discuss it in another issue ? Or if you do not find any usecase, why don't removing this option ? Or at least change the default to False (and update changelog ;) )
