### ISSUE TITLE
Crash when no category is returned by API

### ISSUE THREAD

**Issue by brunetton** [Shinyhero36/Leboncoin-API-Wrapper#4]
```python
from leboncoin_api_wrapper import Leboncoin

lbc = Leboncoin()
lbc.searchFor("Kindle 6", True)
results = lbc.execute()
```

=> TypeError: 'NoneType' object is not subscriptable

I'll have a look

**Comment by brunetton** [comment]
The problem comes from the fact that there's no category returned by API with "Kindle 6" keywords.

- I found that in that case we can just omit `filters.category.id` parameter and this works well
- so I asked myself: is a category mandatory for a request ? And the answer seems to be no: we can totally omit category_id from request 

I don't know if the auto-category feature is super-usefull but I suppose there's some cases that it can help, so I kept it.

**Comment by Shinyhero36** [comment]
There may be some cases when the auto-category feature might be usefull indeed!! 
I'll check later when i am done with classes
